/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.crio.qcalc;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        StandardCalculator var1 = new StandardCalculator();
        var1.add(1, 2);
        var1.printResult();
        var1.subtract(1, 2);
        var1.printResult();
        var1.multiply(1, 2);
        var1.printResult();
        var1.divide(1, 2);
        var1.printResult();
        ScientificCalculator calc = new ScientificCalculator();
        double squareOf = calc.squareOf(5.0);
        System.out.println("square = " + squareOf);
        double cubeOf = calc.cubeOf(3.0);
        System.out.println("cube = " + cubeOf);
        double powerOf = calc.powerOf(2.0, 3.0);
        System.out.println("power = " + powerOf);
        double squareRoot = calc.squareRoot(25.0);
        System.out.println("squareRoot = " + squareRoot);
        int result= calc.modulo(5, 2);
        System.out.println("modulo = " + result);
        double moduloDouble= calc.modulo_double(5.0, 2.0);
        System.out.println("modulo = " + moduloDouble);
    }
}
